const fs = require('fs');
const zhCN = JSON.parse(fs.readFileSync('ui/src/i18n/locales/zh-CN.json', 'utf8'));

// Dashboard translations
zhCN.dashboard = {
  title: "仪表盘",
  welcomeMessage: "欢迎使用 Paperclip。设置您的第一家公司和智能体以开始使用。",
  getStarted: "开始使用",
  selectCompany: "创建或选择一家公司以查看仪表盘。",
  noAgents: "您还没有智能体。",
  createOneHere: "在这里创建",
  activeIncident_one: "{{count}} 个活跃的预算事件",
  activeIncident_other: "{{count}} 个活跃的预算事件",
  budgetIncidentDetails: "{{pausedAgents}} 个智能体已暂停 · {{pausedProjects}} 个项目已暂停 · {{pendingApprovals}} 个待处理的预算审批",
  openBudgets: "查看预算",
  agentsEnabled: "已启用智能体",
  agentsDescription: "{{running}} 个运行中，{{paused}} 个已暂停，{{errors}} 个出错",
  tasksInProgress: "进行中的任务",
  tasksDescription: "{{open}} 个开放，{{blocked}} 个阻塞",
  monthSpend: "本月支出",
  monthSpendDescription: "预算 {{budget}} 的 {{percent}}%",
  unlimitedBudget: "无限预算",
  pendingApprovals: "待审批",
  pendingApprovalsDescription_one: "{{count}} 个预算覆盖等待董事会审批",
  pendingApprovalsDescription_other: "{{count}} 个预算覆盖等待董事会审批",
  awaitingBoardReview: "等待董事会审核",
  runActivity: "运行活动",
  last14Days: "最近 14 天",
  tasksByPriority: "按优先级统计任务",
  tasksByStatus: "按状态统计任务",
  successRate: "成功率",
  recentActivity: "最近活动",
  recentTasks: "最近任务",
  noTasks: "暂无任务。",
  live: {
    breadcrumb: "实时运行",
    createCompany: "创建一家公司以查看实时运行。",
    selectCompany: "选择一家公司以查看实时运行。",
    title: "实时智能体运行",
    description: "活跃运行优先显示，其次是最近完成的运行。",
    showingUpTo: "最多显示 {{limit}} 条",
    activeRecent: "活跃 / 最近",
    noActiveRuns: "没有活跃或最近的智能体运行。"
  }
};

// Agent translations
zhCN.agent = {
  title: "智能体",
  newAgent: "新建智能体",
  count_one: "{{count}} 个智能体",
  count_other: "{{count}} 个智能体",
  noAgents: "创建您的第一个智能体以开始使用。",
  selectCompany: "选择一家公司以查看智能体。",
  noMatchingFilter: "没有智能体匹配所选筛选条件。",
  noOrgHierarchy: "未定义组织层级。",
  invalidReportingChain: "无效的汇报链",
  invalidChainDescription: "{{name}} 无法接受任务或启动运行，直到其汇报链被修复。",
  invalidChainGuidance: "将此智能体分配给活跃的管理员/根，或明确暂停或终止受影响的智能体/子树。",
  repairChainDisabled: "在分配任务或启动运行之前，请修复此智能体的汇报链",
  leftNotice: "您已离开此智能体。它不再出现在您的侧边栏中。",
  pendingApproval: "此智能体正在等待董事会审批，暂时无法调用。",
  approveAgent: "审批智能体",
  live: "实时",
  tabs: {
    all: "全部",
    active: "活跃",
    paused: "已暂停",
    error: "出错",
    dashboard: "仪表盘",
    instructions: "指令",
    skills: "技能",
    configuration: "配置",
    runs: "运行",
    budget: "预算"
  },
  breadcrumb: {
    agents: "智能体",
    runs: "运行",
    run: "运行 {{id}}",
    instructions: "指令",
    configuration: "配置",
    skills: "技能",
    budget: "预算",
    dashboard: "仪表盘"
  },
  actions: {
    assignTask: "分配任务",
    runHeartbeat: "运行心跳",
    runNow: "立即运行",
    resume: "恢复",
    pause: "暂停",
    clearError: "清除错误",
    clearErrorAria: "清除错误并将智能体恢复为空闲",
    duplicateAgent: "复制智能体",
    copyAgentId: "复制智能体 ID",
    resetSessions: "重置会话",
    terminate: "终止",
    openActions: "打开 {{name}} 的操作",
    confirmDuplicate: "将 {{name}} 复制为 {{nextName}}？",
    agentDuplicated: "智能体已复制",
    couldNotDuplicate: "无法复制智能体",
    failedDuplicate: "复制智能体失败",
    notReadyDuplicate: "智能体尚未准备好进行复制",
    failedResetSession: "重置会话失败",
    actionFailed: "操作失败"
  },
  properties: {
    status: "状态",
    errorReason: "错误原因",
    role: "角色",
    title: "头衔",
    adapter: "适配器",
    session: "会话",
    lastError: "上次错误",
    lastRunError: "上次运行错误",
    lastHeartbeat: "上次心跳",
    reportsTo: "汇报对象",
    created: "创建时间"
  },
  overview: {
    runActivity: "运行活动",
    tasksByPriority: "按优先级统计任务",
    tasksByStatus: "按状态统计任务",
    successRate: "成功率",
    last14Days: "最近 14 天",
    recentTasks: "最近任务",
    seeAll: "查看全部",
    noRecentTasks: "暂无最近任务。",
    moreTasks_one: "还有 {{count}} 个任务",
    moreTasks_other: "还有 {{count}} 个任务",
    costs: "成本",
    inputTokens: "输入 token",
    outputTokens: "输出 token",
    cachedTokens: "缓存 token",
    totalCost: "总成本",
    liveRun: "实时运行",
    latestRun: "最新运行",
    viewDetails: "查看详情"
  },
  runs: {
    noRuns: "暂无运行记录。",
    backToRuns: "返回运行列表",
    cancelling: "取消中…",
    cancel: "取消",
    resuming: "恢复中…",
    resume: "恢复",
    retrying: "重试中…",
    retry: "重试",
    transcript: "转录 ({{count}})",
    jumpToLive: "跳转到实时",
    loadingRunLogs: "加载运行日志...",
    noLogEvents: "暂无日志事件。",
    failureDetails: "失败详情",
    errorLabel: "错误：",
    stderr: "标准错误",
    stdout: "标准输出",
    events: "事件 ({{count}})",
    session: "会话",
    changed: "(已更改)",
    before: "之前",
    after: "之后",
    id: "ID",
    clearSessionTasks: "清除这些任务的会话",
    clearingSession: "清除会话中...",
    tasksTouched: "涉及的任务 ({{count}})",
    exitCode: "退出码 {{code}}",
    signal: "信号：{{signal}}",
    failedResume: "恢复运行失败",
    failedRetry: "重试运行失败",
    duration: "时长：{{time}}",
    loadMoreLog: "加载更多日志",
    loading: "加载中...",
    showingFirstKb: "显示前 {{kb}} KB",
    ofKb: "共 {{kb}} KB",
    loginClaude: "登录 Claude Code",
    runningClaudeLogin: "正在运行 claude login...",
    failedClaudeLogin: "运行 Claude 登录失败",
    loginUrl: "登录 URL：",
    failedLoadLog: "加载运行日志失败",
    failedLoadMore: "加载更多运行日志失败",
    failedClearSessions: "清除会话失败",
    confirmClearSessions: "清除此运行涉及的 {{count}} 个议题{{plural}}的会话？",
    input: "输入",
    output: "输出",
    cached: "缓存",
    cost: "成本",
    date: "日期",
    run: "运行"
  },
  invocation: {
    title: "调用",
    adapter: "适配器：",
    workingDir: "工作目录：",
    details: "详情",
    command: "命令：",
    commandNotes: "命令备注",
    prompt: "提示词",
    context: "上下文",
    environment: "环境"
  },
  workspace: {
    title: "工作区 ({{count}})",
    hideLog: "隐藏完整日志",
    showLog: "显示完整日志",
    loadingLog: "加载日志...",
    failedLoadLog: "加载工作区操作日志失败",
    noPersistedLog: "暂无持久化的日志行。",
    createdByRun: "由此运行创建",
    reusedWorkspace: "复用了现有工作区",
    stderrExcerpt: "标准错误摘录",
    stdoutExcerpt: "标准输出摘录",
    command: "命令：",
    workingDir: "工作目录：",
    branch: "分支：",
    baseRef: "基础引用：",
    worktree: "工作树：",
    repoRoot: "仓库根目录：",
    cleanup: "清理："
  },
  instructions: {
    files: "文件",
    create: "创建",
    cancel: "取消",
    delete: "删除",
    deprecatedVirtual: "已弃用的虚拟文件",
    newFile: "此捆绑包中的新文件",
    advanced: "高级",
    mode: "模式",
    managed: "托管",
    external: "外部",
    rootPath: "根路径",
    entryFile: "入口文件",
    localOnly: "指令捆绑包仅适用于本地适配器。",
    confirmDelete: "删除 {{file}}？",
    copyMarkdown: "将指令文件复制为 Markdown",
    copyAsMarkdown: "复制为 Markdown",
    copied: "已复制",
    entry: "入口",
    virtualFileHint: "旧版内联提示词 - 此已弃用的虚拟文件保留了旧的 promptTemplate 内容",
    modeHelp: "托管：Paperclip 存储并提供指令捆绑包。外部：您提供指令所在的磁盘路径。",
    rootPathHelp: "指令捆绑包所在的磁盘绝对目录。在托管模式下，这由 Paperclip 自动设置。",
    entryFileHelp: "智能体加载指令时首先读取的主文件。默认为 AGENTS.md。",
    managedPath: "(托管)",
    fileLanguage: "{{language}} 文件"
  },
  skills: {
    viewLibrary: "查看公司技能库",
    savingChanges: "保存更改...",
    savingSoon: "即将保存...",
    installedSkills: "已安装技能",
    otherSkills: "其他技能",
    unmanagedSkills: "({{count}}) 用户安装的技能，非 Paperclip 管理",
    noInstalledSkills: "此智能体未安装任何公司库技能。",
    importFirst: "请先将技能导入公司库，然后在此处附加。",
    requestedMissing: "请求的技能在公司库中缺失",
    adapter: "适配器",
    skillsApplied: "已应用技能",
    selectedSkills: "已选技能",
    location: "位置：{{location}}",
    view: "查看",
    failedUpdate: "更新技能失败",
    modePersistent: "保留在工作区中",
    modeEphemeral: "智能体运行时应用",
    modeUnsupported: "仅跟踪",
    modeUnknown: "未知",
    unsupportedCustomAcp: "Paperclip 暂时无法管理自定义 ACP 命令的技能。",
    unsupportedOpenClaw: "Paperclip 无法在此管理 OpenClaw 技能。请访问您的 OpenClaw 实例来管理此智能体的技能。",
    unsupportedAdapter: "Paperclip 暂时无法管理此适配器的技能。请直接在适配器中管理。",
    manageInAdapter: "请直接在适配器中管理技能。"
  },
  keys: {
    apiKeyCreated: "API 密钥已创建 - 请立即复制，它不会再次显示。",
    createApiKey: "创建 API 密钥",
    apiKeyDescription: "API 密钥允许此智能体对 Paperclip 服务器进行身份验证调用。",
    keyNamePlaceholder: "密钥名称（例如 production）",
    loadingKeys: "加载密钥...",
    noActiveKeys: "没有活跃的 API 密钥。",
    activeKeys: "活跃密钥",
    created: "创建于 {{date}}",
    revoke: "撤销",
    revokedKeys: "已撤销密钥",
    revoked: "撤销于 {{date}}",
    dismiss: "关闭"
  },
  config: {
    unsavedChanges: "未保存的更改",
    identity: "身份",
    name: "名称",
    title: "头衔",
    reportsTo: "汇报对象",
    capabilities: "能力",
    promptTemplate: "提示词模板",
    agentName: "智能体名称",
    titlePlaceholder: "例如工程副总裁",
    chooseManager: "选择管理者...",
    capabilitiesPlaceholder: "描述此智能体能做什么...",
    promptTemplatePlaceholder: "您是智能体 {{name}}。您的角色是 {{role}}...",
    promptTemplateWarning: "提示词模板在每次心跳时重放。保持简洁和动态，以避免重复的 token 成本和缓存抖动。",
    environment: "环境",
    defaultEnvironment: "默认环境",
    kubernetesHint: "此实例在 Kubernetes 沙箱中运行所有智能体。本地执行已禁用。",
    kubernetesMissing: "此实例需要 Kubernetes 沙箱，但此公司尚无可用的托管 Kubernetes 环境。请在创建智能体之前配置一个；执行不会回退到本地。",
    environmentOverride: "环境覆盖",
    defaultLabel: "默认：{{label}}",
    adapter: "适配器",
    adapterType: "适配器类型",
    test: "测试",
    workingDir: "工作目录（已弃用）",
    permissionsConfig: "权限与配置",
    command: "命令",
    primaryModel: "主模型",
    extraArgs: "额外参数（逗号分隔）",
    envVars: "环境变量",
    timeoutSec: "超时（秒）",
    graceSec: "中断宽限期（秒）",
    runPolicy: "运行策略",
    heartbeatInterval: "定时心跳",
    runHeartbeatEvery: "每多久运行一次心跳",
    sec: "秒",
    advancedRunPolicy: "高级运行策略",
    wakeOnDemand: "按需唤醒",
    cooldownSec: "冷却时间（秒）",
    maxConcurrentRuns: "最大并发运行数",
    continueAfterMaxTurn: "达到最大轮次后继续",
    continuationAttempts: "续接尝试次数",
    continuationDelay: "续接延迟（秒）",
    model: "模型",
    default: "默认",
    selectModelRequired: "选择模型（必填）",
    selectModel: "选择模型",
    searchModels: "搜索模型...",
    searchModelsCreate: "搜索模型...（输入以创建）",
    detectModel: "检测模型",
    reDetectConfig: "从配置重新检测",
    detectFromConfig: "从配置检测",
    detecting: "检测中...",
    refreshModels: "刷新模型",
    refreshing: "刷新中...",
    current: "当前",
    detected: "已检测",
    configBadge: "配置",
    noModelDetected: "尚未检测到模型。请手动输入 provider/model。",
    noModelsFound: "未找到模型。",
    useManualModel: "使用手动模型",
    cheapModel: "经济模型",
    cheapModelHint: "当运行请求经济配置时使用（例如例程摘要）。主模型保持不变。",
    thinkingEffort: "思考强度",
    bootstrapPrompt: "引导提示词（旧版）",
    bootstrapPlaceholder: "首次运行的可选初始设置提示词",
    bootstrapWarning: "引导提示词是旧版功能，将在未来版本中移除。请考虑将此内容移至智能体的提示词模板或指令文件中。",
    passed: "通过",
    warnings: "警告",
    failed: "失败",
    experimental: "实验性",
    comingSoon: "即将推出",
    agentSaved: "智能体已保存",
    saveFailed: "保存失败",
    couldNotSave: "无法保存智能体",
    environmentTestFailed: "环境测试失败",
    failedRefreshModels: "刷新适配器模型失败。",
    failedLoadModels: "加载适配器模型失败。",
    selectCompanySecrets: "选择一家公司以创建密钥",
    selectCompanyImages: "选择一家公司以上传图片",
    selectCompanyTest: "选择一家公司以测试适配器环境",
    noCheapModelFallback: "未选择明确的经济模型 - 运行时回退到 {{model}}。",
    noCheapModelWarning: "未选择经济模型且适配器无默认值。经济通道运行将在主模型上继续，并附带回退说明。",
    adapterDefault: "适配器默认 - {{model}}",
    noAdapterDefault: "无适配器默认值 - 请选择更便宜的模型",
    permissions: "权限",
    canCreateAgents: "可以创建新智能体",
    canCreateAgentsHint: "允许此智能体创建或招聘智能体，并隐式分配任务。",
    canAssignTasks: "可以分配任务",
    ceoAutoEnabled: "CEO 智能体自动启用。",
    agentCreatorAutoEnabled: "当此智能体可以创建新智能体时自动启用。",
    explicitGrant: "通过明确的公司权限授予启用。",
    simpleDefault: "通过简单的公司范围任务分配默认值启用。",
    disabledUnlessGranted: "除非明确授予，否则禁用。",
    codexMinimalWarning: "Codex 在启用搜索时可能拒绝 minimal 思考模式。",
    opencodeModelDiscovery: "实时 OpenCode 模型发现仅在本地环境运行。为 {{name}} 使用精选列表和手动输入。",
    configRevisions: "配置修订",
    noConfigRevisions: "暂无配置修订。",
    restore: "恢复",
    changed: "已更改：",
    noTrackedChanges: "无跟踪的更改"
  }
};

fs.writeFileSync('ui/src/i18n/locales/zh-CN.json', JSON.stringify(zhCN, null, 2) + '\n');
console.log('Updated zh-CN.json with Chinese translations.');

// Count total keys
function countKeys(obj) {
  let count = 0;
  for (const value of Object.values(obj)) {
    if (typeof value === 'object' && value !== null) {
      count += countKeys(value);
    } else {
      count++;
    }
  }
  return count;
}
console.log('Total zh-CN keys:', countKeys(zhCN));
