const fs = require('fs');
const path = require('path');
const dir = 'ui/src/i18n/locales';
const zh = JSON.parse(fs.readFileSync(path.join(dir, 'zh-CN.json'), 'utf8'));

function s(obj, keyPath, val) {
  const keys = keyPath.split('.');
  let c = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!c[keys[i]] || typeof c[keys[i]] !== 'object') c[keys[i]] = {};
    c = c[keys[i]];
  }
  c[keys[keys.length - 1]] = val;
}

// ============ secrets (remaining) ============
const sc = [
  ['secrets.page.title', '密钥管理'],
  ['secrets.page.selectCompany', '选择一个公司以管理密钥。'],
  ['secrets.page.providerVaults', '提供商保险库'],
  ['secrets.table.name', '名称'],
  ['secrets.table.mode', '模式'],
  ['secrets.table.provider', '提供商'],
  ['secrets.table.status', '状态'],
  ['secrets.table.version', '版本'],
  ['secrets.table.lastRotated', '最后轮换'],
  ['secrets.table.lastResolved', '最后解析'],
  ['secrets.table.references', '引用'],
  ['secrets.table.reference', '引用'],
  ['secrets.table.open', '打开'],
  ['secrets.table.owned', '拥有'],
  ['secrets.search.placeholder', '按名称、密钥、引用搜索'],
  ['secrets.search.ariaLabel', '搜索密钥'],
  ['secrets.button.newSecret', '新建密钥'],
  ['secrets.button.retry', '重试'],
  ['secrets.button.disable', '禁用'],
  ['secrets.button.activate', '激活'],
  ['secrets.button.unarchive', '取消归档'],
  ['secrets.button.archive', '归档'],
  ['secrets.button.delete', '删除'],
  ['secrets.button.cancel', '取消'],
  ['secrets.button.createSecret', '创建密钥'],
  ['secrets.button.linkReference', '关联引用'],
  ['secrets.button.updateValue', '更新值'],
  ['secrets.button.updateReference', '更新引用'],
  ['secrets.button.saveVault', '保存保险库'],
  ['secrets.button.createVault', '创建保险库'],
  ['secrets.button.checkHealth', '检查健康状态'],
  ['secrets.button.makeDefault', '设为默认'],
  ['secrets.button.remove', '移除'],
  ['secrets.button.addVault', '添加保险库'],
  ['secrets.button.importFromVault', '从保险库导入'],
  ['secrets.button.manageVaults', '管理保险库'],
  ['secrets.toast.secretCreated', '密钥已创建'],
  ['secrets.toast.rotated', '已轮换'],
  ['secrets.toast.rotateFailed', '轮换失败'],
  ['secrets.toast.statusUpdated', '密钥 {{status}}'],
  ['secrets.toast.statusUpdateFailed', '状态更新失败'],
  ['secrets.toast.tryAgain', '请重试'],
  ['secrets.toast.secretDeleted', '密钥已删除'],
  ['secrets.toast.deleteFailed', '删除失败'],
  ['secrets.toast.vaultUpdated', '提供商保险库已更新'],
  ['secrets.toast.vaultCreated', '提供商保险库已创建'],
  ['secrets.toast.vaultDisabled', '提供商保险库已禁用'],
  ['secrets.toast.disableFailed', '禁用失败'],
  ['secrets.toast.vaultRemoved', '提供商保险库已移除'],
  ['secrets.toast.removeFailed', '移除失败'],
  ['secrets.toast.defaultVaultSet', '已设为默认保险库'],
  ['secrets.toast.defaultUpdateFailed', '更新默认失败'],
  ['secrets.toast.healthChecked', '健康检查完成'],
  ['secrets.toast.healthCheckFailed', '健康检查失败'],
  ['secrets.dialog.createTitle', '创建密钥'],
  ['secrets.dialog.createDescription', '选择 Paperclip 是否应拥有未来的提供商写入，还是仅在运行时解析现有的提供商引用。'],
  ['secrets.dialog.updateExternalTitle', '更新外部引用'],
  ['secrets.dialog.updateValueTitle', '更新密钥值'],
  ['secrets.dialog.deleteTitle', '删除密钥'],
  ['secrets.dialog.deleteDesc', '永久删除 {{name}}。活跃绑定将失败，直到您重新映射它们。'],
  ['secrets.dialog.vaultTitle', '密钥引用'],
  ['secrets.dialog.vaultDesc', '{{name}} 被 {{count}} {{unit}} 引用。'],
  ['secrets.dialog.editVaultTitle', '编辑提供商保险库'],
  ['secrets.dialog.createVaultTitle', '创建提供商保险库'],
  ['secrets.dialog.removeVaultTitle', '移除提供商保险库'],
  ['secrets.dialog.removeVaultDesc', '仅从 Paperclip 移除 {{name}}。'],
  ['secrets.dialog.removeFromPaperclip', '从 Paperclip 移除'],
  ['secrets.filter.filters', '筛选'],
  ['secrets.filter.clear', '清除'],
  ['secrets.filter.status', '状态'],
  ['secrets.filter.provider', '提供商'],
  ['secrets.filter.active', '活跃'],
  ['secrets.filter.allStatuses', '所有状态'],
  ['secrets.filter.disabled', '已禁用'],
  ['secrets.filter.archived', '已归档'],
  ['secrets.filter.allProviders', '所有提供商'],
  ['secrets.tab.details', '详情'],
  ['secrets.tab.usage', '使用情况'],
  ['secrets.tab.accessEvents', '访问事件'],
  ['secrets.empty.noSecrets', '暂无密钥。创建您的第一个托管密钥或关联外部引用。'],
  ['secrets.empty.noFilterMatch', '没有密钥匹配您的筛选条件。'],
  ['secrets.empty.failedToLoad', '加载密钥失败：'],
  ['secrets.empty.loadingVaults', '加载提供商保险库'],
  ['secrets.empty.failedToLoadVaults', '加载提供商保险库失败：'],
  ['secrets.empty.noVaults', '暂无公司特定保险库。密钥仍可使用部署默认提供商设置。'],
  ['secrets.info.howToUseTitle', '通过将密钥绑定到运行时环境变量来使用。'],
  ['secrets.info.howToUseBody', '在此处创建或关联密钥，然后打开代理的环境变量或项目的环境字段。添加进程期望的环境键，例如 <code>GH_TOKEN</code>，选择<bold>密钥</bold>，并选择存储的密钥版本。'],
  ['secrets.managed.paperclipManaged', 'Paperclip 托管'],
  ['secrets.managed.linkedExternal', '关联外部'],
  ['secrets.managed.paperclipManagedDesc', 'Paperclip 拥有此提供商密钥的创建和轮换写入。'],
  ['secrets.managed.linkedExternalDesc', 'Paperclip 解析此提供商引用但不轮换提供商值。'],
  ['secrets.form.name', '名称'],
  ['secrets.form.key', '密钥'],
  ['secrets.form.provider', '提供商'],
  ['secrets.form.value', '值'],
  ['secrets.form.description', '描述'],
  ['secrets.form.newValue', '新值'],
  ['secrets.form.updatedReference', '更新的引用'],
  ['secrets.form.ready', '就绪'],
  ['secrets.form.warning', '警告'],
  ['secrets.form.comingSoon', '即将推出'],
  ['secrets.detailsTab.description', '描述'],
  ['secrets.detailsTab.custody', '托管'],
  ['secrets.detailsTab.provider', '提供商'],
  ['secrets.detailsTab.providerVault', '提供商保险库'],
  ['secrets.detailsTab.latestVersion', '最新版本'],
  ['secrets.detailsTab.created', '创建时间'],
  ['secrets.detailsTab.updated', '更新时间'],
  ['secrets.detailsTab.lastRotated', '最后轮换'],
  ['secrets.detailsTab.lastResolved', '最后解析'],
  ['secrets.detailsTab.linkedProviderRef', '关联的提供商引用'],
  ['secrets.detailsTab.providerManagedPath', '提供商托管路径'],
  ['secrets.usageTab.loading', '加载中...'],
  ['secrets.usageTab.noBindings', '无活跃绑定。在代理、项目、环境或插件配置中添加此密钥以开始使用。'],
  ['secrets.usageTab.required', '必填'],
  ['secrets.usageTab.optional', '可选'],
  ['secrets.eventsTab.loading', '加载中...'],
  ['secrets.eventsTab.noEvents', '暂无访问事件记录。每次运行时解析都会在此处写入一个编辑条目。'],
  ['secrets.awsDiscovery.title', 'AWS 发现'],
  ['secrets.awsDiscovery.description', '使用当前草稿路由字段检查 AWS Secrets Manager 元数据。不会读取值。'],
  ['secrets.awsDiscovery.findExisting', '查找现有 AWS 值'],
  ['secrets.awsDiscovery.searchingMetadata', '搜索 AWS Secrets Manager 元数据'],
  ['secrets.awsDiscovery.noCandidates', '未找到 AWS 保险库元数据候选。仍可手动输入。'],
  ['secrets.awsDiscovery.useValues', '使用值'],
  ['secrets.vaultCard.defaultVault', '默认保险库'],
  ['secrets.vaultCard.vault', '保险库'],
  ['secrets.vaultCard.health', '健康状态'],
  ['secrets.vaultCard.healthNotChecked', '未检查健康状态'],
  ['secrets.vaultsTab.comingSoon', '即将推出'],
  ['secrets.howToUse.title', '通过将密钥绑定到运行时环境变量来使用。'],
  ['secrets.howToUse.body1', '在此处创建或关联密钥，然后打开代理的环境变量或项目的环境字段。'],
  ['secrets.howToUse.body2', 'Paperclip 在运行开始时在服务端解析值并将其注入为该环境变量。'],
];
for (const [k, v] of sc) s(zh, k, v);

// ============ plugin (remaining) ============
const pl = [
  ['plugin.settings.loadingDetails', '加载详情中...'],
  ['plugin.settings.pluginDetails', '插件详情'],
  ['plugin.settings.configuration', '配置'],
  ['plugin.settings.status', '状态'],
  ['plugin.about.title', '关于'],
  ['plugin.about.description', '描述'],
  ['plugin.about.author', '作者'],
  ['plugin.about.categories', '分类'],
  ['plugin.about.none', '无'],
  ['plugin.envDriver.configureFromEnvironments', '从环境配置'],
  ['plugin.envDriver.envDriverDesc', '环境驱动描述'],
  ['plugin.envDriver.thisPlugin', '此插件'],
  ['plugin.envDriver.openEnvironments', '打开环境'],
  ['plugin.envDriver.noSettings', '无设置'],
  ['plugin.dashboard.title', '仪表板'],
  ['plugin.dashboard.description', '描述'],
  ['plugin.dashboard.workerProcess', '工作进程'],
  ['plugin.dashboard.status', '状态'],
  ['plugin.dashboard.pid', 'PID'],
  ['plugin.dashboard.uptime', '运行时间'],
  ['plugin.dashboard.pendingRpcs', '待处理 RPC'],
  ['plugin.dashboard.crashes', '崩溃次数'],
  ['plugin.dashboard.consecutiveTotal', '连续/总计'],
  ['plugin.dashboard.lastCrash', '最后崩溃'],
  ['plugin.dashboard.noWorker', '无工作进程'],
  ['plugin.dashboard.recentJobRuns', '最近任务运行'],
  ['plugin.dashboard.noJobRuns', '无任务运行记录'],
  ['plugin.dashboard.recentWebhooks', '最近 Webhook'],
  ['plugin.dashboard.noWebhooks', '无 Webhook 记录'],
  ['plugin.dashboard.lastChecked', '最后检查'],
  ['plugin.dashboard.unavailable', '不可用'],
  ['plugin.logs.title', '日志'],
  ['plugin.logs.lastEntries', '最后条目'],
  ['plugin.health.title', '健康检查'],
  ['plugin.health.checking', '检查中...'],
  ['plugin.health.overall', '总体'],
  ['plugin.health.lifecycle', '生命周期'],
  ['plugin.health.checksRunWhenReady', '就绪时运行检查'],
  ['plugin.details.title', '详情'],
  ['plugin.details.pluginId', '插件 ID'],
  ['plugin.details.pluginKey', '插件键'],
  ['plugin.details.npmPackage', 'npm 包'],
  ['plugin.details.version', '版本'],
  ['plugin.permissions.title', '权限'],
  ['plugin.permissions.noPermissions', '无权限'],
  ['plugin.localFolders.selectCompany', '选择公司'],
  ['plugin.localFolders.title', '本地文件夹'],
  ['plugin.localFolders.failedToLoad', '加载失败'],
  ['plugin.localFolders.loading', '加载中...'],
  ['plugin.localFolders.healthy', '健康'],
  ['plugin.localFolders.needsAttention', '需要关注'],
  ['plugin.localFolders.readWrite', '读写'],
  ['plugin.localFolders.readOnly', '只读'],
  ['plugin.localFolders.configured', '已配置'],
  ['plugin.localFolders.yes', '是'],
  ['plugin.localFolders.no', '否'],
  ['plugin.localFolders.readable', '可读'],
  ['plugin.localFolders.writable', '可写'],
  ['plugin.localFolders.configuredPath', '配置路径'],
  ['plugin.localFolders.localFolderPath', '本地文件夹路径'],
  ['plugin.localFolders.pathPlaceholder', '路径'],
  ['plugin.localFolders.save', '保存'],
  ['plugin.localFolders.validationProblems', '验证问题'],
  ['plugin.localFolders.savedOk', '保存成功'],
  ['plugin.localFolders.saveFailed', '保存失败'],
  ['plugin.localFolders.pathRequired', '路径必填'],
  ['plugin.localFolders.mustBeAbsolutePath', '必须是绝对路径'],
  ['plugin.localFolders.requiredDirs', '必需目录'],
  ['plugin.localFolders.requiredFiles', '必需文件'],
  ['plugin.localFolders.missingDirs', '缺失目录'],
  ['plugin.localFolders.missingFiles', '缺失文件'],
  ['plugin.localFolders.present', '存在'],
  ['plugin.localFolders.noneDeclared', '未声明'],
  ['plugin.configForm.loading', '加载中...'],
  ['plugin.configForm.saved', '已保存'],
  ['plugin.configForm.saveFailed', '保存失败'],
  ['plugin.configForm.testPassed', '测试通过'],
  ['plugin.configForm.testFailed', '测试失败'],
  ['plugin.configForm.saveConfig', '保存配置'],
  ['plugin.configForm.saving', '保存中...'],
  ['plugin.configForm.testConfig', '测试配置'],
  ['plugin.configForm.testing', '测试中...'],
  ['plugin.installDialog.title', '安装插件'],
  ['plugin.installDialog.description', '输入要安装的插件的 npm 包名。'],
  ['plugin.installDialog.packageName', 'npm 包名'],
  ['plugin.installDialog.install', '安装'],
  ['plugin.installDialog.installing', '安装中...'],
  ['plugin.installDialog.cancel', '取消'],
  ['plugin.uninstallDialog.title', '卸载插件'],
  ['plugin.uninstallDialog.confirm', '确定要卸载 {{name}} 吗？'],
  ['plugin.uninstallDialog.warning', '此操作无法撤销。'],
  ['plugin.uninstallDialog.uninstall', '卸载'],
  ['plugin.uninstallDialog.uninstalling', '卸载中...'],
  ['plugin.uninstallDialog.cancel', '取消'],
  ['plugin.errorDialog.title', '错误详情'],
  ['plugin.errorDialog.errorState', '{{name}} 进入错误状态。'],
  ['plugin.errorDialog.whatErrored', '错误原因'],
  ['plugin.errorDialog.noErrorSummary', '无错误摘要。'],
  ['plugin.errorDialog.fullErrorOutput', '完整错误输出'],
  ['plugin.errorDialog.noStoredError', '无存储的错误消息。'],
  ['plugin.errorDialog.close', '关闭'],
  ['plugin.toast.installSuccess', '插件安装成功'],
  ['plugin.toast.installError', '安装插件失败'],
  ['plugin.toast.uninstallSuccess', '插件已卸载'],
  ['plugin.toast.uninstallError', '卸载插件失败'],
  ['plugin.toast.enableSuccess', '插件已启用'],
  ['plugin.toast.enableError', '启用插件失败'],
  ['plugin.toast.disableSuccess', '插件已禁用'],
  ['plugin.toast.disableError', '禁用插件失败'],
];
for (const [k, v] of pl) s(zh, k, v);

// ============ project (remaining) ============
const pj = [
  ['project.title', '项目'],
  ['project.noProjects', '暂无项目'],
  ['project.create', '创建项目'],
  ['project.name', '名称'],
  ['project.description', '描述'],
  ['project.status', '状态'],
  ['project.priority', '优先级'],
  ['project.owner', '所有者'],
  ['project.members', '成员'],
  ['project.labels', '标签'],
  ['project.createdAt', '创建时间'],
  ['project.updatedAt', '更新时间'],
  ['project.loading', '加载中...'],
  ['project.error', '加载失败'],
  ['project.retry', '重试'],
  ['project.edit', '编辑'],
  ['project.delete', '删除'],
  ['project.deleteConfirm', '确定要删除此项目吗？'],
  ['project.archive', '归档'],
  ['project.unarchive', '取消归档'],
  ['project.search', '搜索项目'],
  ['project.filter', '筛选'],
  ['project.sort', '排序'],
  ['project.view', '视图'],
  ['project.details', '详情'],
  ['project.settings', '设置'],
  ['project.issues', '问题'],
  ['project.workspaces', '工作区'],
  ['project.documents', '文档'],
  ['project.activity', '活动'],
  ['project.overview', '概览'],
  ['project.localFolder', '本地文件夹'],
  ['project.repoUrl', '仓库 URL'],
  ['project.repoUrlError', '仓库 URL 无效'],
  ['project.localFolderError', '本地文件夹路径无效'],
  ['project.statusBacklog', '待办'],
  ['project.statusPlanned', '已计划'],
  ['project.statusInProgress', '进行中'],
  ['project.statusCompleted', '已完成'],
  ['project.statusCancelled', '已取消'],
  ['project.noDescription', '无描述'],
  ['project.noOwner', '无所有者'],
  ['project.noMembers', '无成员'],
  ['project.noLabels', '无标签'],
  ['project.addMember', '添加成员'],
  ['project.removeMember', '移除成员'],
  ['project.addLabel', '添加标签'],
  ['project.removeLabel', '移除标签'],
  ['project.setOwner', '设置所有者'],
  ['project.changeStatus', '更改状态'],
  ['project.changePriority', '更改优先级'],
];
for (const [k, v] of pj) s(zh, k, v);

// ============ costs ============
const co = [
  ['costs.title', '成本'],
  ['costs.loading', '加载中...'],
  ['costs.error', '加载失败'],
  ['costs.retry', '重试'],
  ['costs.total', '总计'],
  ['costs.period', '周期'],
  ['costs.daily', '每日'],
  ['costs.weekly', '每周'],
  ['costs.monthly', '每月'],
  ['costs.yearly', '每年'],
  ['costs.custom', '自定义'],
  ['costs.from', '从'],
  ['costs.to', '到'],
  ['costs.apply', '应用'],
  ['costs.reset', '重置'],
  ['costs.export', '导出'],
  ['costs.refresh', '刷新'],
  ['costs.noData', '暂无数据'],
  ['costs.breakdown', '明细'],
  ['costs.byAgent', '按代理'],
  ['costs.byProject', '按项目'],
  ['costs.byModel', '按模型'],
  ['costs.byUser', '按用户'],
  ['costs.byTask', '按任务'],
  ['costs.tokens', '令牌'],
  ['costs.inputTokens', '输入令牌'],
  ['costs.outputTokens', '输出令牌'],
  ['costs.totalTokens', '总令牌'],
  ['costs.cost', '成本'],
  ['costs.averageCost', '平均成本'],
  ['costs.totalCost', '总成本'],
  ['costs.projectedCost', '预计成本'],
  ['costs.budget', '预算'],
  ['costs.budgetUsed', '已用预算'],
  ['costs.budgetRemaining', '剩余预算'],
  ['costs.budgetExceeded', '预算超支'],
  ['costs.alerts', '告警'],
  ['costs.noAlerts', '暂无告警'],
  ['costs.settings', '设置'],
  ['costs.save', '保存'],
  ['costs.cancel', '取消'],
  ['costs.saved', '已保存'],
  ['costs.saveFailed', '保存失败'],
  ['costs.chart', '图表'],
  ['costs.table', '表格'],
  ['costs.trend', '趋势'],
  ['costs.comparison', '对比'],
  ['costs.current', '当前'],
  ['costs.previous', '上一期'],
  ['costs.change', '变化'],
  ['costs.percentage', '百分比'],
  ['costs.increase', '增加'],
  ['costs.decrease', '减少'],
  ['costs.noChange', '无变化'],
];
for (const [k, v] of co) s(zh, k, v);

// ============ inbox (remaining) ============
const ib = [
  ['inbox.title', '收件箱'],
  ['inbox.loading', '加载中...'],
  ['inbox.error', '加载失败'],
  ['inbox.retry', '重试'],
  ['inbox.empty', '收件箱为空'],
  ['inbox.noItems', '暂无项目'],
  ['inbox.markAsRead', '标记为已读'],
  ['inbox.markAsUnread', '标记为未读'],
  ['inbox.markAllAsRead', '全部标记为已读'],
  ['inbox.archive', '归档'],
  ['inbox.archiveAll', '全部归档'],
  ['inbox.delete', '删除'],
  ['inbox.deleteAll', '全部删除'],
  ['inbox.refresh', '刷新'],
  ['inbox.filter', '筛选'],
  ['inbox.sort', '排序'],
  ['inbox.groupBy', '分组'],
  ['inbox.search', '搜索'],
  ['inbox.noResults', '未找到结果'],
  ['inbox.clearFilters', '清除筛选'],
  ['inbox.select', '选择'],
  ['inbox.selectAll', '全选'],
  ['inbox.deselectAll', '取消全选'],
  ['inbox.bulkActions', '批量操作'],
  ['inbox.selected', '已选择'],
  ['inbox.view', '视图'],
  ['inbox.listView', '列表视图'],
  ['inbox.boardView', '看板视图'],
  ['inbox.unread', '未读'],
  ['inbox.read', '已读'],
  ['inbox.all', '全部'],
  ['inbox.today', '今天'],
  ['inbox.yesterday', '昨天'],
  ['inbox.thisWeek', '本周'],
  ['inbox.lastWeek', '上周'],
  ['inbox.older', '更早'],
];
for (const [k, v] of ib) s(zh, k, v);

// ============ artifact (remaining) ============
const ar = [
  ['artifact.title', '产物'],
  ['artifact.noArtifacts', '暂无产物'],
  ['artifact.loading', '加载中...'],
  ['artifact.error', '加载失败'],
  ['artifact.retry', '重试'],
  ['artifact.search', '搜索产物'],
  ['artifact.filter', '筛选'],
  ['artifact.sort', '排序'],
  ['artifact.view', '查看'],
  ['artifact.download', '下载'],
  ['artifact.delete', '删除'],
  ['artifact.deleteConfirm', '确定要删除此产物吗？'],
  ['artifact.name', '名称'],
  ['artifact.type', '类型'],
  ['artifact.size', '大小'],
  ['artifact.createdAt', '创建时间'],
  ['artifact.updatedAt', '更新时间'],
  ['artifact.createdBy', '创建者'],
  ['artifact.project', '项目'],
  ['artifact.issue', '问题'],
  ['artifact.preview', '预览'],
  ['artifact.details', '详情'],
  ['artifact.metadata', '元数据'],
  ['artifact.tags', '标签'],
  ['artifact.addTag', '添加标签'],
  ['artifact.removeTag', '移除标签'],
  ['artifact.share', '分享'],
  ['artifact.copyLink', '复制链接'],
  ['artifact.linkCopied', '链接已复制'],
  ['artifact.export', '导出'],
  ['artifact.import', '导入'],
  ['artifact.upload', '上传'],
  ['artifact.uploading', '上传中...'],
  ['artifact.uploadFailed', '上传失败'],
  ['artifact.tooLarge', '文件太大'],
  ['artifact.invalidType', '无效的文件类型'],
  ['artifact.version', '版本'],
  ['artifact.history', '历史'],
  ['artifact.restore', '恢复'],
  ['artifact.restoreConfirm', '确定要恢复此版本吗？'],
];
for (const [k, v] of ar) s(zh, k, v);

// ============ search (remaining) ============
const se = [
  ['search.title', '搜索'],
  ['search.placeholder', '搜索...'],
  ['search.noResults', '未找到结果'],
  ['search.loading', '搜索中...'],
  ['search.error', '搜索失败'],
  ['search.retry', '重试'],
  ['search.filter', '筛选'],
  ['search.clear', '清除'],
  ['search.scope', '范围'],
  ['search.all', '全部'],
  ['search.issues', '问题'],
  ['search.projects', '项目'],
  ['search.agents', '代理'],
  ['search.routines', '例程'],
  ['search.documents', '文档'],
  ['search.users', '用户'],
  ['search.sort', '排序'],
  ['search.relevance', '相关性'],
  ['search.date', '日期'],
  ['search.name', '名称'],
  ['search.type', '类型'],
  ['search.viewAll', '查看全部'],
  ['search.openFullSearch', '打开完整搜索'],
  ['search.recent', '最近搜索'],
  ['search.clearRecent', '清除最近搜索'],
  ['search.suggestions', '建议'],
  ['search.noSuggestions', '无建议'],
  ['search.advanced', '高级搜索'],
  ['search.savedSearches', '已保存的搜索'],
  ['search.saveSearch', '保存搜索'],
  ['search.deleteSearch', '删除搜索'],
];
for (const [k, v] of se) {
  if (v !== undefined) s(zh, k, v);
}

fs.writeFileSync(path.join(dir, 'zh-CN.json'), JSON.stringify(zh, null, 2) + '\n');
console.log('Batch C done: secrets, plugin, project, costs, inbox, artifact, search translated.');
