const fs = require('fs');
const path = require('path');
const dir = 'ui/src/i18n/locales';
const zh = JSON.parse(fs.readFileSync(path.join(dir, 'zh-CN.json'), 'utf8'));

function set(obj, keyPath, val) {
  const keys = keyPath.split('.');
  let c = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!c[keys[i]] || typeof c[keys[i]] !== 'object') c[keys[i]] = {};
    c = c[keys[i]];
  }
  c[keys[keys.length - 1]] = val;
}

// ============ issue.chat ============
set(zh, 'issue.chat.title', '聊天');
set(zh, 'issue.chat.placeholder', '输入消息...');
set(zh, 'issue.chat.send', '发送');
set(zh, 'issue.chat.sending', '发送中...');
set(zh, 'issue.chat.noMessages', '暂无消息');
set(zh, 'issue.chat.loadMore', '加载更多');
set(zh, 'issue.chat.loading', '加载中...');
set(zh, 'issue.chat.error', '加载失败');
set(zh, 'issue.chat.retry', '重试');
set(zh, 'issue.chat.delete', '删除');
set(zh, 'issue.chat.deleteConfirm', '确定要删除此消息吗？');
set(zh, 'issue.chat.deleted', '消息已删除');
set(zh, 'issue.chat.edit', '编辑');
set(zh, 'issue.chat.reply', '回复');
set(zh, 'issue.chat.copy', '复制');
set(zh, 'issue.chat.copied', '已复制');
set(zh, 'issue.chat.copyFailed', '复制失败');
set(zh, 'issue.chat.followUp', '追问');
set(zh, 'issue.chat.running', '运行中');
set(zh, 'issue.chat.interrupt', '中断');
set(zh, 'issue.chat.interrupting', '中断中...');
set(zh, 'issue.chat.cancel', '取消');
set(zh, 'issue.chat.viewRun', '查看运行');
set(zh, 'issue.chat.moreActions', '更多操作');
set(zh, 'issue.chat.helpful', '有帮助');
set(zh, 'issue.chat.needsWork', '需要改进');
set(zh, 'issue.chat.feedbackSubmitted', '反馈已提交');
set(zh, 'issue.chat.shareFeedback', '分享反馈');
set(zh, 'issue.chat.feedbackPlaceholder', '告诉我们您的想法...');
set(zh, 'issue.chat.submit', '提交');
set(zh, 'issue.chat.close', '关闭');
set(zh, 'issue.chat.assistantMessage', '助手消息');
set(zh, 'issue.chat.userMessage', '用户消息');
set(zh, 'issue.chat.systemMessage', '系统消息');
set(zh, 'issue.chat.thinking', '思考中...');
set(zh, 'issue.chat.paused', '已暂停');
set(zh, 'issue.chat.pausedNotice', '代理已暂停');
set(zh, 'issue.chat.resume', '恢复');
set(zh, 'issue.chat.resuming', '恢复中...');
set(zh, 'issue.chat.assignee', '负责人');
set(zh, 'issue.chat.status', '状态');
set(zh, 'issue.chat.messageDeleted', '消息已删除');
set(zh, 'issue.chat.confirmDelete', '确认删除');
set(zh, 'issue.chat.copyMessage', '复制消息');
set(zh, 'issue.chat.deleteComment', '删除评论');
set(zh, 'issue.chat.shareDialog', '分享对话');
set(zh, 'issue.chat.shareDialogDesc', '分享此对话给其他人。');
set(zh, 'issue.chat.linkCopied', '链接已复制');
set(zh, 'issue.chat.copyLink', '复制链接');
set(zh, 'issue.chat.downloadChat', '下载聊天记录');
set(zh, 'issue.chat.chatHistory', '聊天历史');
set(zh, 'issue.chat.emptyChat', '聊天为空');
set(zh, 'issue.chat.startConversation', '开始对话');
set(zh, 'issue.chat.agentTyping', '代理正在输入...');
set(zh, 'issue.chat.waitForResponse', '请等待回复');
set(zh, 'issue.chat.messageSent', '消息已发送');
set(zh, 'issue.chat.sendFailed', '发送失败');
set(zh, 'issue.chat.connectionLost', '连接已断开');
set(zh, 'issue.chat.reconnecting', '重新连接中...');
set(zh, 'issue.chat.reconnected', '已重新连接');
set(zh, 'issue.chat.noAssignee', '未分配');

// ============ issue.propertiesPage ============
set(zh, 'issue.propertiesPage.title', '属性');
set(zh, 'issue.propertiesPage.status', '状态');
set(zh, 'issue.propertiesPage.priority', '优先级');
set(zh, 'issue.propertiesPage.assignee', '负责人');
set(zh, 'issue.propertiesPage.labels', '标签');
set(zh, 'issue.propertiesPage.project', '项目');
set(zh, 'issue.propertiesPage.milestone', '里程碑');
set(zh, 'issue.propertiesPage.dueDate', '截止日期');
set(zh, 'issue.propertiesPage.estimatedTime', '预估时间');
set(zh, 'issue.propertiesPage.actualTime', '实际时间');
set(zh, 'issue.propertiesPage.created', '创建时间');
set(zh, 'issue.propertiesPage.updated', '更新时间');
set(zh, 'issue.propertiesPage.closed', '关闭时间');
set(zh, 'issue.propertiesPage.started', '开始时间');
set(zh, 'issue.propertiesPage.completed', '完成时间');
set(zh, 'issue.propertiesPage.cancelled', '取消时间');
set(zh, 'issue.propertiesPage.archived', '归档时间');
set(zh, 'issue.propertiesPage.parent', '父任务');
set(zh, 'issue.propertiesPage.children', '子任务');
set(zh, 'issue.propertiesPage.dependencies', '依赖项');
set(zh, 'issue.propertiesPage.blockedBy', '被阻塞于');
set(zh, 'issue.propertiesPage.blocks', '阻塞');
set(zh, 'issue.propertiesPage.relatedTo', '关联');
set(zh, 'issue.propertiesPage.references', '引用');
set(zh, 'issue.propertiesPage.attachments', '附件');
set(zh, 'issue.propertiesPage.comments', '评论');
set(zh, 'issue.propertiesPage.activity', '活动');
set(zh, 'issue.propertiesPage.timeline', '时间线');
set(zh, 'issue.propertiesPage.details', '详情');
set(zh, 'issue.propertiesPage.metadata', '元数据');
set(zh, 'issue.propertiesPage.customFields', '自定义字段');
set(zh, 'issue.propertiesPage.noCustomFields', '暂无自定义字段');
set(zh, 'issue.propertiesPage.edit', '编辑');
set(zh, 'issue.propertiesPage.save', '保存');
set(zh, 'issue.propertiesPage.cancel', '取消');
set(zh, 'issue.propertiesPage.saved', '已保存');
set(zh, 'issue.propertiesPage.saveFailed', '保存失败');
set(zh, 'issue.propertiesPage.loading', '加载中...');
set(zh, 'issue.propertiesPage.error', '加载失败');
set(zh, 'issue.propertiesPage.retry', '重试');
set(zh, 'issue.propertiesPage.noProject', '无项目');
set(zh, 'issue.propertiesPage.noLabels', '无标签');
set(zh, 'issue.propertiesPage.noMilestone', '无里程碑');
set(zh, 'issue.propertiesPage.noDueDate', '无截止日期');
set(zh, 'issue.propertiesPage.noParent', '无父任务');
set(zh, 'issue.propertiesPage.noChildren', '无子任务');
set(zh, 'issue.propertiesPage.noDependencies', '无依赖项');
set(zh, 'issue.propertiesPage.noReferences', '无引用');
set(zh, 'issue.propertiesPage.noAttachments', '无附件');
set(zh, 'issue.propertiesPage.addLabel', '添加标签');
set(zh, 'issue.propertiesPage.removeLabel', '移除标签');
set(zh, 'issue.propertiesPage.addDependency', '添加依赖');
set(zh, 'issue.propertiesPage.removeDependency', '移除依赖');
set(zh, 'issue.propertiesPage.linkIssue', '关联问题');
set(zh, 'issue.propertiesPage.unlinkIssue', '取消关联');
set(zh, 'issue.propertiesPage.changeStatus', '更改状态');
set(zh, 'issue.propertiesPage.changePriority', '更改优先级');
set(zh, 'issue.propertiesPage.changeAssignee', '更改负责人');
set(zh, 'issue.propertiesPage.setDueDate', '设置截止日期');
set(zh, 'issue.propertiesPage.clearDueDate', '清除截止日期');
set(zh, 'issue.propertiesPage.archive', '归档');
set(zh, 'issue.propertiesPage.unarchive', '取消归档');
set(zh, 'issue.propertiesPage.delete', '删除');
set(zh, 'issue.propertiesPage.deleteConfirm', '确定要删除此问题吗？');
set(zh, 'issue.propertiesPage.deleteWarning', '此操作无法撤销。');

// ============ issue.newDialog ============
set(zh, 'issue.newDialog.title', '新建问题');
set(zh, 'issue.newDialog.nameLabel', '问题名称');
set(zh, 'issue.newDialog.namePlaceholder', '输入问题名称...');
set(zh, 'issue.newDialog.descriptionLabel', '描述');
set(zh, 'issue.newDialog.descriptionPlaceholder', '添加描述...');
set(zh, 'issue.newDialog.statusLabel', '状态');
set(zh, 'issue.newDialog.priorityLabel', '优先级');
set(zh, 'issue.newDialog.assigneeLabel', '负责人');
set(zh, 'issue.newDialog.projectLabel', '项目');
set(zh, 'issue.newDialog.labelsLabel', '标签');
set(zh, 'issue.newDialog.dueDateLabel', '截止日期');
set(zh, 'issue.newDialog.create', '创建');
set(zh, 'issue.newDialog.creating', '创建中...');
set(zh, 'issue.newDialog.cancel', '取消');
set(zh, 'issue.newDialog.error', '创建失败');
set(zh, 'issue.newDialog.success', '问题已创建');
set(zh, 'issue.newDialog.advanced', '高级选项');
set(zh, 'issue.newDialog.basic', '基本信息');
set(zh, 'issue.newDialog.preview', '预览');
set(zh, 'issue.newDialog.submit', '提交');
set(zh, 'issue.newDialog.reset', '重置');

// ============ issue.runLedger ============
set(zh, 'issue.runLedger.title', '运行记录');
set(zh, 'issue.runLedger.noRuns', '暂无运行记录');
set(zh, 'issue.runLedger.loading', '加载中...');
set(zh, 'issue.runLedger.error', '加载失败');
set(zh, 'issue.runLedger.retry', '重试');
set(zh, 'issue.runLedger.runId', '运行 ID');
set(zh, 'issue.runLedger.status', '状态');
set(zh, 'issue.runLedger.startedAt', '开始时间');
set(zh, 'issue.runLedger.completedAt', '完成时间');
set(zh, 'issue.runLedger.duration', '持续时间');
set(zh, 'issue.runLedger.agent', '代理');
set(zh, 'issue.runLedger.model', '模型');
set(zh, 'issue.runLedger.tokens', '令牌');
set(zh, 'issue.runLedger.cost', '成本');
set(zh, 'issue.runLedger.viewDetails', '查看详情');
set(zh, 'issue.runLedger.viewLogs', '查看日志');
set(zh, 'issue.runLedger.viewOutput', '查看输出');
set(zh, 'issue.runLedger.rerun', '重新运行');
set(zh, 'issue.runLedger.cancel', '取消');
set(zh, 'issue.runLedger.cancelled', '已取消');
set(zh, 'issue.runLedger.running', '运行中');
set(zh, 'issue.runLedger.completed', '已完成');
set(zh, 'issue.runLedger.failed', '失败');
set(zh, 'issue.runLedger.pending', '待处理');
set(zh, 'issue.runLedger.queued', '已排队');
set(zh, 'issue.runLedger.skipped', '已跳过');
set(zh, 'issue.runLedger.success', '成功');
set(zh, 'issue.runLedger.filter', '筛选');
set(zh, 'issue.runLedger.clearFilter', '清除筛选');
set(zh, 'issue.runLedger.search', '搜索');
set(zh, 'issue.runLedger.export', '导出');
set(zh, 'issue.runLedger.refresh', '刷新');

// ============ issue.toasts ============
set(zh, 'issue.toasts.created', '问题已创建');
set(zh, 'issue.toasts.updated', '问题已更新');
set(zh, 'issue.toasts.deleted', '问题已删除');
set(zh, 'issue.toasts.archived', '问题已归档');
set(zh, 'issue.toasts.restored', '问题已恢复');
set(zh, 'issue.toasts.statusChanged', '状态已更改');
set(zh, 'issue.toasts.priorityChanged', '优先级已更改');
set(zh, 'issue.toasts.assigneeChanged', '负责人已更改');
set(zh, 'issue.toasts.labelAdded', '标签已添加');
set(zh, 'issue.toasts.labelRemoved', '标签已移除');
set(zh, 'issue.toasts.commentAdded', '评论已添加');
set(zh, 'issue.toasts.commentDeleted', '评论已删除');
set(zh, 'issue.toasts.attachmentAdded', '附件已添加');
set(zh, 'issue.toasts.attachmentDeleted', '附件已删除');
set(zh, 'issue.toasts.error', '操作失败');
set(zh, 'issue.toasts.retry', '重试');
set(zh, 'issue.toasts.undo', '撤销');
set(zh, 'issue.toasts.saveSuccess', '保存成功');
set(zh, 'issue.toasts.saveFailed', '保存失败');
set(zh, 'issue.toasts.deleteFailed', '删除失败');
set(zh, 'issue.toasts.loadFailed', '加载失败');
set(zh, 'issue.toasts.networkError', '网络错误');
set(zh, 'issue.toasts.permissionDenied', '权限不足');
set(zh, 'issue.toasts.notFound', '未找到');
set(zh, 'issue.toasts.unknownError', '未知错误');

// ============ issue.recovery ============
set(zh, 'issue.recovery.title', '恢复');
set(zh, 'issue.recovery.description', '任务需要恢复操作。');
set(zh, 'issue.recovery.action', '恢复操作');
set(zh, 'issue.recovery.actions', '恢复选项');
set(zh, 'issue.recovery.retry', '重试');
set(zh, 'issue.recovery.retrying', '重试中...');
set(zh, 'issue.recovery.skip', '跳过');
set(zh, 'issue.recovery.abort', '中止');
set(zh, 'issue.recovery.ignore', '忽略');
set(zh, 'issue.recovery.escalate', '升级');
set(zh, 'issue.recovery.delegate', '委托');
set(zh, 'issue.recovery.manual', '手动处理');
set(zh, 'issue.recovery.auto', '自动处理');
set(zh, 'issue.recovery.suggested', '建议');
set(zh, 'issue.recovery.viewDetails', '查看详情');
set(zh, 'issue.recovery.viewHistory', '查看历史');
set(zh, 'issue.recovery.noRecovery', '无需恢复');
set(zh, 'issue.recovery.recoveryFailed', '恢复失败');
set(zh, 'issue.recovery.recoverySuccess', '恢复成功');
set(zh, 'issue.recovery.pending', '待处理');
set(zh, 'issue.recovery.inProgress', '进行中');
set(zh, 'issue.recovery.completed', '已完成');
set(zh, 'issue.recovery.failed', '失败');
set(zh, 'issue.recovery.reason', '原因');
set(zh, 'issue.recovery.details', '详情');

// ============ issue.treeControl ============
set(zh, 'issue.treeControl.title', '任务树');
set(zh, 'issue.treeControl.expand', '展开');
set(zh, 'issue.treeControl.collapse', '折叠');
set(zh, 'issue.treeControl.expandAll', '全部展开');
set(zh, 'issue.treeControl.collapseAll', '全部折叠');
set(zh, 'issue.treeControl.addChild', '添加子任务');
set(zh, 'issue.treeControl.removeChild', '移除子任务');
set(zh, 'issue.treeControl.reorder', '重新排序');
set(zh, 'issue.treeControl.indent', '缩进');
set(zh, 'issue.treeControl.outdent', '取消缩进');
set(zh, 'issue.treeControl.noChildren', '无子任务');
set(zh, 'issue.treeControl.loading', '加载中...');
set(zh, 'issue.treeControl.error', '加载失败');
set(zh, 'issue.treeControl.dragToReorder', '拖拽重新排序');
set(zh, 'issue.treeControl.viewTree', '查看树');
set(zh, 'issue.treeControl.viewList', '查看列表');
set(zh, 'issue.treeControl.viewBoard', '查看看板');

// ============ issue.list ============
set(zh, 'issue.list.title', '问题列表');
set(zh, 'issue.list.noIssues', '暂无问题');
set(zh, 'issue.list.loading', '加载中...');
set(zh, 'issue.list.error', '加载失败');
set(zh, 'issue.list.retry', '重试');
set(zh, 'issue.list.search', '搜索问题');
set(zh, 'issue.list.filter', '筛选');
set(zh, 'issue.list.sort', '排序');
set(zh, 'issue.list.groupBy', '分组');
set(zh, 'issue.list.view', '视图');
set(zh, 'issue.list.listView', '列表');
set(zh, 'issue.list.boardView', '看板');
set(zh, 'issue.list.treeView', '树');
set(zh, 'issue.list.refresh', '刷新');
set(zh, 'issue.list.selectAll', '全选');
set(zh, 'issue.list.deselectAll', '取消全选');
set(zh, 'issue.list.bulkActions', '批量操作');
set(zh, 'issue.list.bulkEdit', '批量编辑');
set(zh, 'issue.list.bulkDelete', '批量删除');
set(zh, 'issue.list.bulkArchive', '批量归档');
set(zh, 'issue.list.selected', '已选择');
set(zh, 'issue.list.noResults', '未找到结果');
set(zh, 'issue.list.clearFilters', '清除筛选');
set(zh, 'issue.list.saveView', '保存视图');
set(zh, 'issue.list.loadView', '加载视图');
set(zh, 'issue.list.defaultView', '默认视图');

// ============ issue.status ============
set(zh, 'issue.status.backlog', '待办');
set(zh, 'issue.status.todo', '待处理');
set(zh, 'issue.status.inProgress', '进行中');
set(zh, 'issue.status.inReview', '审查中');
set(zh, 'issue.status.done', '已完成');
set(zh, 'issue.status.cancelled', '已取消');
set(zh, 'issue.status.blocked', '阻塞');
set(zh, 'issue.status.archived', '已归档');
set(zh, 'issue.status.open', '打开');
set(zh, 'issue.status.closed', '关闭');
set(zh, 'issue.status.reopened', '已重新打开');
set(zh, 'issue.status.draft', '草稿');
set(zh, 'issue.status.ready', '就绪');
set(zh, 'issue.status.parked', '暂停');
set(zh, 'issue.status.waiting', '等待中');
set(zh, 'issue.status.scheduled', '已计划');
set(zh, 'issue.status.running', '运行中');
set(zh, 'issue.status.paused', '已暂停');
set(zh, 'issue.status.failed', '失败');

// ============ issue.runActions ============
set(zh, 'issue.runActions.title', '运行操作');
set(zh, 'issue.runActions.start', '开始');
set(zh, 'issue.runActions.stop', '停止');
set(zh, 'issue.runActions.restart', '重启');
set(zh, 'issue.runActions.pause', '暂停');
set(zh, 'issue.runActions.resume', '恢复');
set(zh, 'issue.runActions.cancel', '取消');
set(zh, 'issue.runActions.retry', '重试');
set(zh, 'issue.runActions.viewLogs', '查看日志');
set(zh, 'issue.runActions.viewOutput', '查看输出');
set(zh, 'issue.runActions.viewDetails', '查看详情');
set(zh, 'issue.runActions.delete', '删除');

// ============ issue.filters ============
set(zh, 'issue.filters.title', '筛选');
set(zh, 'issue.filters.status', '状态');
set(zh, 'issue.filters.priority', '优先级');
set(zh, 'issue.filters.assignee', '负责人');
set(zh, 'issue.filters.project', '项目');
set(zh, 'issue.filters.labels', '标签');
set(zh, 'issue.filters.dateRange', '日期范围');
set(zh, 'issue.filters.hasAssignee', '有负责人');
set(zh, 'issue.filters.noAssignee', '无负责人');
set(zh, 'issue.filters.hasProject', '有项目');
set(zh, 'issue.filters.noProject', '无项目');
set(zh, 'issue.filters.hasLabels', '有标签');
set(zh, 'issue.filters.noLabels', '无标签');
set(zh, 'issue.filters.isBlocked', '被阻塞');
set(zh, 'issue.filters.isReady', '就绪');
set(zh, 'issue.filters.isArchived', '已归档');
set(zh, 'issue.filters.clear', '清除');
set(zh, 'issue.filters.apply', '应用');
set(zh, 'issue.filters.save', '保存');
set(zh, 'issue.filters.reset', '重置');

fs.writeFileSync(path.join(dir, 'zh-CN.json'), JSON.stringify(zh, null, 2) + '\n');
console.log('Batch A done: issue section translated.');
