const fs = require('fs');
const path = require('path');
const dir = 'ui/src/i18n/locales';
const zh = JSON.parse(fs.readFileSync(path.join(dir, 'zh-CN.json'), 'utf8'));

function s(obj, keyPath, val) {
  const keys = keyPath.split('.');
  let c = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!c[keys[i]] || typeof c[keys[i]] !== 'object') c[keys[i]] = {};
    c = c[keys[i]];
  }
  c[keys[keys.length - 1]] = val;
}

// ============ onboarding ============
const ob = [
  ['onboarding.welcome', '欢迎使用 Paperclip'],
  ['onboarding.getStarted', '开始使用'],
  ['onboarding.setupAgent', '设置代理'],
  ['onboarding.chooseAdapter', '选择适配器'],
  ['onboarding.configureEnvironment', '配置环境'],
  ['onboarding.testConnection', '测试连接'],
  ['onboarding.connectionSuccess', '连接成功'],
  ['onboarding.connectionFailed', '连接失败'],
  ['onboarding.next', '下一步'],
  ['onboarding.back', '返回'],
  ['onboarding.skip', '跳过'],
  ['onboarding.finish', '完成'],
  ['onboarding.loading', '加载中...'],
  ['onboarding.error', '出错了'],
  ['onboarding.retry', '重试'],
  ['onboarding.missionPrompt', '任务提示'],
  ['onboarding.selectModel', '选择模型'],
  ['onboarding.apiKey', 'API 密钥'],
  ['onboarding.apiKeyPlaceholder', '输入您的 API 密钥'],
  ['onboarding.baseUrl', '基础 URL'],
  ['onboarding.baseUrlPlaceholder', '输入基础 URL（可选）'],
  ['onboarding.testing', '测试中...'],
  ['onboarding.test', '测试'],
  ['onboarding.save', '保存'],
  ['onboarding.saved', '已保存'],
  ['onboarding.saveFailed', '保存失败'],
  ['onboarding.recommended', '推荐'],
  ['onboarding.advanced', '高级'],
  ['onboarding.basic', '基础'],
];
for (const [k, v] of ob) s(zh, k, v);

// ============ onboardingClassic ============
const oc = [
  ['onboardingClassic.title', '入门设置'],
  ['onboardingClassic.subtitle', '让我们帮您设置环境。'],
  ['onboardingClassic.step1', '步骤 1：选择提供商'],
  ['onboardingClassic.step2', '步骤 2：输入凭据'],
  ['onboardingClassic.step3', '步骤 3：验证设置'],
  ['onboardingClassic.step4', '步骤 4：完成'],
  ['onboardingClassic.selectProvider', '选择提供商'],
  ['onboardingClassic.enterCredentials', '输入凭据'],
  ['onboardingClassic.verifySetup', '验证设置'],
  ['onboardingClassic.success', '设置完成'],
  ['onboardingClassic.successDescription', '您的环境已准备就绪。'],
  ['onboardingClassic.goToDashboard', '前往仪表板'],
  ['onboardingClassic.next', '下一步'],
  ['onboardingClassic.back', '返回'],
  ['onboardingClassic.skip', '跳过'],
  ['onboardingClassic.finish', '完成'],
  ['onboardingClassic.loading', '加载中...'],
  ['onboardingClassic.error', '出错了'],
  ['onboardingClassic.retry', '重试'],
  ['onboardingClassic.save', '保存'],
  ['onboardingClassic.saved', '已保存'],
  ['onboardingClassic.saveFailed', '保存失败'],
  ['onboardingClassic.test', '测试'],
  ['onboardingClassic.testing', '测试中...'],
  ['onboardingClassic.testSuccess', '测试成功'],
  ['onboardingClassic.testFailed', '测试失败'],
  ['onboardingClassic.apiKey', 'API 密钥'],
  ['onboardingClassic.apiKeyPlaceholder', '输入您的 API 密钥'],
  ['onboardingClassic.baseUrl', '基础 URL'],
  ['onboardingClassic.baseUrlPlaceholder', '输入基础 URL（可选）'],
  ['onboardingClassic.selectModel', '选择模型'],
  ['onboardingClassic.noModels', '无可用模型'],
  ['onboardingClassic.recommended', '推荐'],
  ['onboardingClassic.optional', '可选'],
  ['onboardingClassic.required', '必填'],
  ['onboardingClassic.errors.apiKeyRequired', 'API 密钥必填'],
  ['onboardingClassic.errors.modelRequired', '请选择模型'],
  ['onboardingClassic.errors.connectionFailed', '连接失败'],
  ['onboardingClassic.errors.invalidApiKey', 'API 密钥无效'],
  ['onboardingClassic.errors.invalidBaseUrl', '基础 URL 无效'],
  ['onboardingClassic.errors.timeout', '连接超时'],
  ['onboardingClassic.errors.unknown', '未知错误'],
  ['onboardingClassic.errors.retry', '重试'],
  ['onboardingClassic.tabs.model', '模型'],
  ['onboardingClassic.tabs.environment', '环境'],
  ['onboardingClassic.tabs.advanced', '高级'],
  ['onboardingClassic.footer.poweredBy', '由 Paperclip 驱动'],
  ['onboardingClassic.footer.privacy', '隐私政策'],
  ['onboardingClassic.footer.terms', '服务条款'],
  ['onboardingClassic.adapterResult.title', '适配器结果'],
  ['onboardingClassic.adapterResult.success', '配置成功'],
  ['onboardingClassic.adapterResult.failed', '配置失败'],
  ['onboardingClassic.adapterResult.details', '详情'],
  ['onboardingClassic.adapterResult.retry', '重试'],
];
for (const [k, v] of oc) s(zh, k, v);

// ============ onboardingChat ============
const oca = [
  ['onboardingChat.title', '开始对话'],
  ['onboardingChat.subtitle', '让我帮您设置。'],
  ['onboardingChat.placeholder', '输入您的需求...'],
  ['onboardingChat.send', '发送'],
  ['onboardingChat.thinking', '思考中...'],
  ['onboardingChat.error', '出错了'],
  ['onboardingChat.retry', '重试'],
  ['onboardingChat.skip', '跳过'],
  ['onboardingChat.done', '完成'],
  ['onboardingChat.welcomeMessage.title', '欢迎'],
  ['onboardingChat.welcomeMessage.subtitle', '让我帮您开始。'],
  ['onboardingChat.welcomeMessage.getStarted', '开始使用'],
  ['onboardingChat.welcomeMessage.learnMore', '了解更多'],
  ['onboardingChat.welcomeMessage.skip', '跳过设置'],
  ['onboardingChat.welcomeMessage.or', '或'],
  ['onboardingChat.welcomeMessage.importSettings', '导入设置'],
  ['onboardingChat.welcomeMessage.description', '告诉我您想做什么，我会帮您设置。'],
];
for (const [k, v] of oca) s(zh, k, v);

// ============ teamCatalog ============
const tc = [
  ['teamCatalog.title', '团队目录'],
  ['teamCatalog.noTeams', '暂无团队'],
  ['teamCatalog.createTeam', '创建团队'],
  ['teamCatalog.loading', '加载中...'],
  ['teamCatalog.error', '加载失败'],
  ['teamCatalog.retry', '重试'],
  ['teamCatalog.search', '搜索团队'],
  ['teamCatalog.filter', '筛选'],
  ['teamCatalog.sort', '排序'],
  ['teamCatalog.name', '名称'],
  ['teamCatalog.description', '描述'],
  ['teamCatalog.members', '成员'],
  ['teamCatalog.install', '安装'],
  ['teamCatalog.uninstall', '卸载'],
  ['teamCatalog.configure', '配置'],
  ['teamCatalog.settings', '设置'],
  ['teamCatalog.details', '详情'],
  ['teamCatalog.targets', '目标'],
  ['teamCatalog.sources', '来源'],
  ['teamCatalog.skills', '技能'],
  ['teamCatalog.preview', '预览'],
  ['teamCatalog.apply', '应用'],
  ['teamCatalog.applying', '应用中...'],
  ['teamCatalog.success', '成功'],
  ['teamCatalog.failed', '失败'],
  ['teamCatalog.cancel', '取消'],
  ['teamCatalog.save', '保存'],
  ['teamCatalog.saved', '已保存'],
  ['teamCatalog.saveFailed', '保存失败'],
  ['teamCatalog.delete', '删除'],
  ['teamCatalog.deleteConfirm', '确定要删除此团队吗？'],
  ['teamCatalog.deleted', '团队已删除'],
  ['teamCatalog.deleteFailed', '删除失败'],
  ['teamCatalog.enable', '启用'],
  ['teamCatalog.disable', '禁用'],
  ['teamCatalog.enabled', '已启用'],
  ['teamCatalog.disabled', '已禁用'],
  ['teamCatalog.version', '版本'],
  ['teamCatalog.author', '作者'],
  ['teamCatalog.tags', '标签'],
  ['teamCatalog.category', '分类'],
  ['teamCatalog.rating', '评分'],
  ['teamCatalog.downloads', '下载次数'],
  ['teamCatalog.lastUpdated', '最后更新'],
  ['teamCatalog.compatibility', '兼容性'],
  ['teamCatalog.requirements', '要求'],
  ['teamCatalog.documentation', '文档'],
  ['teamCatalog.source', '源码'],
  ['teamCatalog.license', '许可证'],
  ['teamCatalog.dependencies', '依赖'],
  ['teamCatalog.changelog', '更新日志'],
  ['teamCatalog.issues', '问题'],
  ['teamCatalog.support', '支持'],
  ['teamCatalog.feedback', '反馈'],
  ['teamCatalog.overview', '概览'],
  ['teamCatalog.configuration', '配置'],
  ['teamCatalog.permissions', '权限'],
  ['teamCatalog.health', '健康状态'],
  ['teamCatalog.status', '状态'],
  ['teamCatalog.active', '活跃'],
  ['teamCatalog.inactive', '不活跃'],
  ['teamCatalog.installed', '已安装'],
  ['teamCatalog.available', '可用'],
  ['teamCatalog.updates', '更新'],
  ['teamCatalog.update', '更新'],
  ['teamCatalog.updating', '更新中...'],
  ['teamCatalog.updated', '已更新'],
  ['teamCatalog.updateFailed', '更新失败'],
  ['teamCatalog.rollback', '回滚'],
  ['teamCatalog.rollbackConfirm', '确定要回滚到上一版本吗？'],
  ['teamCatalog.rolledBack', '已回滚'],
  ['teamCatalog.rollbackFailed', '回滚失败'],
  ['teamCatalog.logs', '日志'],
  ['teamCatalog.viewLogs', '查看日志'],
  ['teamCatalog.export', '导出'],
  ['teamCatalog.import', '导入'],
  ['teamCatalog.clone', '克隆'],
  ['teamCatalog.share', '分享'],
  ['teamCatalog.copyLink', '复制链接'],
  ['teamCatalog.linkCopied', '链接已复制'],
];
for (const [k, v] of tc) s(zh, k, v);

// ============ inviteLanding ============
const il = [
  ['inviteLanding.title', '邀请'],
  ['inviteLanding.description', '您已被邀请加入。'],
  ['inviteLanding.accept', '接受邀请'],
  ['inviteLanding.decline', '拒绝'],
  ['inviteLanding.loading', '加载中...'],
  ['inviteLanding.error', '加载邀请失败'],
  ['inviteLanding.expired', '邀请已过期'],
  ['inviteLanding.invalid', '邀请无效'],
  ['inviteLanding.accepted', '邀请已接受'],
  ['inviteLanding.declined', '邀请已拒绝'],
  ['inviteLanding.loginToAccept', '登录以接受邀请'],
  ['inviteLanding.registerToAccept', '注册以接受邀请'],
  ['inviteLanding.alreadyMember', '您已经是成员'],
  ['inviteLanding.pending', '邀请待处理'],
  ['inviteLanding.invitedBy', '邀请者'],
  ['inviteLanding.invitedAt', '邀请时间'],
  ['inviteLanding.role', '角色'],
  ['inviteLanding.permissions', '权限'],
  ['inviteLanding.company', '公司'],
  ['inviteLanding.message', '消息'],
  ['inviteLanding.noMessage', '无消息'],
  ['inviteLanding.accepting', '接受中...'],
  ['inviteLanding.declining', '拒绝中...'],
  ['inviteLanding.acceptFailed', '接受失败'],
  ['inviteLanding.declineFailed', '拒绝失败'],
  ['inviteLanding.redirecting', '跳转中...'],
  ['inviteLanding.welcome', '欢迎加入'],
  ['inviteLanding.getStarted', '开始使用'],
  ['inviteLanding.goToDashboard', '前往仪表板'],
  ['inviteLanding.learnMore', '了解更多'],
  ['inviteLanding.contactSupport', '联系支持'],
  ['inviteLanding.termsOfService', '服务条款'],
  ['inviteLanding.privacyPolicy', '隐私政策'],
  ['inviteLanding.iAgree', '我同意'],
  ['inviteLanding.iDisagree', '我不同意'],
  ['inviteLanding.mustAgree', '必须同意条款才能继续'],
];
for (const [k, v] of il) s(zh, k, v);

// ============ executionWorkspace.close (remaining) ============
const ew = [
  ['executionWorkspace.close.title', '关闭工作区'],
  ['executionWorkspace.close.description', '关闭前请完成或确认以下事项。'],
  ['executionWorkspace.close.archive', '归档'],
  ['executionWorkspace.close.cancel', '取消'],
  ['executionWorkspace.close.confirm', '确认关闭'],
  ['executionWorkspace.close.blockingTasks', '阻塞任务'],
  ['executionWorkspace.close.warnings', '警告'],
  ['executionWorkspace.close.gitStatus', 'Git 状态'],
  ['executionWorkspace.close.branch', '分支'],
  ['executionWorkspace.close.uncommittedChanges', '未提交的更改'],
  ['executionWorkspace.close.files', '文件'],
  ['executionWorkspace.close.staged', '已暂存'],
  ['executionWorkspace.close.unstaged', '未暂存'],
  ['executionWorkspace.close.untracked', '未跟踪'],
  ['executionWorkspace.close.commitMessage', '提交消息'],
  ['executionWorkspace.close.commitMessagePlaceholder', '输入提交消息...'],
  ['executionWorkspace.close.commitAndClose', '提交并关闭'],
  ['executionWorkspace.close.discardAndClose', '丢弃并关闭'],
  ['executionWorkspace.close.noBlockingTasks', '无阻塞任务。'],
  ['executionWorkspace.close.noWarnings', '无警告。'],
  ['executionWorkspace.close.ready', '就绪'],
  ['executionWorkspace.close.notReady', '未就绪'],
  ['executionWorkspace.close.loading', '加载中...'],
  ['executionWorkspace.close.error', '错误'],
  ['executionWorkspace.close.success', '成功'],
  ['executionWorkspace.close.failed', '失败'],
  ['executionWorkspace.close.retry', '重试'],
  ['executionWorkspace.close.force', '强制'],
  ['executionWorkspace.close.forceClose', '强制关闭'],
  ['executionWorkspace.close.forceCloseWarning', '强制关闭可能会丢失未保存的工作。'],
  ['executionWorkspace.close.saveDraft', '保存草稿'],
  ['executionWorkspace.close.discardDraft', '丢弃草稿'],
  ['executionWorkspace.close.unsavedChanges', '有未保存的更改'],
  ['executionWorkspace.close.unsavedChangesWarning', '您有未保存的更改。确定要关闭吗？'],
];
for (const [k, v] of ew) s(zh, k, v);

// ============ userProfile (remaining) ============
const up = [
  ['userProfile.title', '个人资料'],
  ['userProfile.name', '名称'],
  ['userProfile.email', '邮箱'],
  ['userProfile.avatar', '头像'],
  ['userProfile.save', '保存'],
  ['userProfile.cancel', '取消'],
  ['userProfile.saved', '已保存'],
  ['userProfile.error', '保存失败'],
  ['userProfile.loading', '加载中...'],
  ['userProfile.changePassword', '修改密码'],
  ['userProfile.currentPassword', '当前密码'],
  ['userProfile.newPassword', '新密码'],
  ['userProfile.confirmPassword', '确认密码'],
  ['userProfile.passwordMismatch', '密码不匹配'],
  ['userProfile.passwordChanged', '密码已修改'],
  ['userProfile.deleteAccount', '删除账户'],
  ['userProfile.deleteAccountConfirm', '确定要删除您的账户吗？此操作无法撤销。'],
  ['userProfile.usage', '使用情况'],
  ['userProfile.activity', '活动'],
  ['userProfile.preferences', '偏好设置'],
  ['userProfile.windowColumn.title', '窗口列'],
  ['userProfile.windowColumn.description', '配置窗口列显示。'],
  ['userProfile.windowColumn.add', '添加列'],
  ['userProfile.windowColumn.remove', '移除列'],
  ['userProfile.windowColumn.reorder', '重新排序'],
  ['userProfile.windowColumn.save', '保存'],
  ['userProfile.windowColumn.cancel', '取消'],
  ['userProfile.windowColumn.reset', '重置为默认'],
  ['userProfile.windowColumn.name', '名称'],
  ['userProfile.windowColumn.width', '宽度'],
  ['userProfile.windowColumn.visible', '可见'],
  ['userProfile.heroStats.title', '统计概览'],
  ['userProfile.heroStats.tasksCompleted', '已完成任务'],
  ['userProfile.heroStats.activeProjects', '活跃项目'],
  ['userProfile.heroStats.totalCost', '总成本'],
  ['userProfile.heroStats.uptime', '运行时间'],
  ['userProfile.heroStats.loading', '加载中...'],
  ['userProfile.heroStats.error', '加载失败'],
  ['userProfile.usageChart.title', '使用图表'],
  ['userProfile.usageChart.period', '周期'],
  ['userProfile.usageChart.loading', '加载中...'],
  ['userProfile.usageChart.error', '加载失败'],
  ['userProfile.usageChart.noData', '暂无数据'],
];
for (const [k, v] of up) s(zh, k, v);

// ============ inbox.groupBy ============
s(zh, 'inbox.groupBy.status', '按状态');
s(zh, 'inbox.groupBy.priority', '按优先级');
s(zh, 'inbox.groupBy.assignee', '按负责人');
s(zh, 'inbox.groupBy.project', '按项目');
s(zh, 'inbox.groupBy.date', '按日期');
s(zh, 'inbox.groupBy.type', '按类型');
s(zh, 'inbox.groupBy.none', '不分组');

fs.writeFileSync(path.join(dir, 'zh-CN.json'), JSON.stringify(zh, null, 2) + '\n');
console.log('Batch D done: onboarding, teamCatalog, inviteLanding, executionWorkspace, userProfile translated.');
