const fs = require('fs');
const path = require('path');
const dir = 'ui/src/i18n/locales';
const zh = JSON.parse(fs.readFileSync(path.join(dir, 'zh-CN.json'), 'utf8'));

function s(obj, keyPath, val) {
  const keys = keyPath.split('.');
  let c = obj;
  for (let i = 0; i < keys.length - 1; i++) {
    if (!c[keys[i]] || typeof c[keys[i]] !== 'object') c[keys[i]] = {};
    c = c[keys[i]];
  }
  c[keys[keys.length - 1]] = val;
}

// ============ companySettings ============
const cs = [
  ['companySettings.general.title', '通用设置'],
  ['companySettings.general.name', '公司名称'],
  ['companySettings.general.slug', '公司标识'],
  ['companySettings.general.description', '描述'],
  ['companySettings.general.logo', 'Logo'],
  ['companySettings.general.save', '保存'],
  ['companySettings.general.saved', '已保存'],
  ['companySettings.general.saveFailed', '保存失败'],
  ['companySettings.general.loading', '加载中...'],
  ['companySettings.general.error', '加载失败'],
  ['companySettings.members.title', '成员管理'],
  ['companySettings.members.noMembers', '暂无成员'],
  ['companySettings.members.invite', '邀请成员'],
  ['companySettings.members.remove', '移除'],
  ['companySettings.members.role', '角色'],
  ['companySettings.members.joinedAt', '加入时间'],
  ['companySettings.members.loading', '加载中...'],
  ['companySettings.members.error', '加载失败'],
  ['companySettings.members.inviteSent', '邀请已发送'],
  ['companySettings.members.inviteFailed', '发送邀请失败'],
  ['companySettings.members.removeConfirm', '确定要移除此成员吗？'],
  ['companySettings.members.removed', '成员已移除'],
  ['companySettings.members.removeFailed', '移除失败'],
  ['companySettings.access.title', '访问控制'],
  ['companySettings.access.loading', '加载中...'],
  ['companySettings.access.error', '加载失败'],
  ['companySettings.access.roles', '角色'],
  ['companySettings.access.permissions', '权限'],
  ['companySettings.access.addRole', '添加角色'],
  ['companySettings.access.editRole', '编辑角色'],
  ['companySettings.access.deleteRole', '删除角色'],
  ['companySettings.access.deleteConfirm', '确定要删除此角色吗？'],
  ['companySettings.access.roleName', '角色名称'],
  ['companySettings.access.roleDescription', '角色描述'],
  ['companySettings.access.save', '保存'],
  ['companySettings.access.cancel', '取消'],
  ['companySettings.access.saved', '已保存'],
  ['companySettings.access.saveFailed', '保存失败'],
  ['companySettings.environments.title', '环境管理'],
  ['companySettings.environments.noEnvironments', '暂无环境'],
  ['companySettings.environments.create', '创建环境'],
  ['companySettings.environments.name', '名称'],
  ['companySettings.environments.description', '描述'],
  ['companySettings.environments.variables', '变量'],
  ['companySettings.environments.addVariable', '添加变量'],
  ['companySettings.environments.removeVariable', '移除变量'],
  ['companySettings.environments.save', '保存'],
  ['companySettings.environments.cancel', '取消'],
  ['companySettings.environments.saved', '已保存'],
  ['companySettings.environments.saveFailed', '保存失败'],
  ['companySettings.environments.delete', '删除'],
  ['companySettings.environments.deleteConfirm', '确定要删除此环境吗？'],
  ['companySettings.environments.deleted', '环境已删除'],
  ['companySettings.environments.deleteFailed', '删除失败'],
  ['companySettings.environments.loading', '加载中...'],
  ['companySettings.environments.error', '加载失败'],
  ['companySettings.invites.title', '邀请管理'],
  ['companySettings.invites.noInvites', '暂无邀请'],
  ['companySettings.invites.send', '发送邀请'],
  ['companySettings.invites.email', '邮箱'],
  ['companySettings.invites.role', '角色'],
  ['companySettings.invites.status', '状态'],
  ['companySettings.invites.sentAt', '发送时间'],
  ['companySettings.invites.expiresAt', '过期时间'],
  ['companySettings.invites.resend', '重新发送'],
  ['companySettings.invites.revoke', '撤销'],
  ['companySettings.invites.revokeConfirm', '确定要撤销此邀请吗？'],
  ['companySettings.invites.revoked', '邀请已撤销'],
  ['companySettings.invites.revokeFailed', '撤销失败'],
  ['companySettings.invites.loading', '加载中...'],
  ['companySettings.invites.error', '加载失败'],
  ['companySettings.export.title', '导出'],
  ['companySettings.export.description', '导出公司数据。'],
  ['companySettings.export.export', '导出'],
  ['companySettings.export.exporting', '导出中...'],
  ['companySettings.export.success', '导出成功'],
  ['companySettings.export.error', '导出失败'],
  ['companySettings.export.format', '格式'],
  ['companySettings.export.includeAgents', '包含代理'],
  ['companySettings.export.includeProjects', '包含项目'],
  ['companySettings.export.includeRoutines', '包含例程'],
  ['companySettings.import.title', '导入'],
  ['companySettings.import.description', '导入公司数据。'],
  ['companySettings.import.import', '导入'],
  ['companySettings.import.importing', '导入中...'],
  ['companySettings.import.success', '导入成功'],
  ['companySettings.import.error', '导入失败'],
  ['companySettings.import.selectFile', '选择文件'],
  ['companySettings.import.preview', '预览'],
  ['companySettings.import.confirm', '确认导入'],
  ['companySettings.import.cancel', '取消'],
  ['companySettings.skills.title', '技能管理'],
  ['companySettings.skills.noSkills', '暂无技能'],
  ['companySettings.skills.create', '创建技能'],
  ['companySettings.skills.name', '名称'],
  ['companySettings.skills.description', '描述'],
  ['companySettings.skills.type', '类型'],
  ['companySettings.skills.status', '状态'],
  ['companySettings.skills.enable', '启用'],
  ['companySettings.skills.disable', '禁用'],
  ['companySettings.skills.edit', '编辑'],
  ['companySettings.skills.delete', '删除'],
  ['companySettings.skills.deleteConfirm', '确定要删除此技能吗？'],
  ['companySettings.skills.save', '保存'],
  ['companySettings.skills.cancel', '取消'],
  ['companySettings.skills.saved', '已保存'],
  ['companySettings.skills.saveFailed', '保存失败'],
  ['companySettings.skills.loading', '加载中...'],
  ['companySettings.skills.error', '加载失败'],
];
for (const [k, v] of cs) s(zh, k, v);

// ============ skills ============
const sk = [
  ['skills.title', '技能'],
  ['skills.noSkills', '暂无技能'],
  ['skills.create', '创建技能'],
  ['skills.name', '名称'],
  ['skills.description', '描述'],
  ['skills.type', '类型'],
  ['skills.status', '状态'],
  ['skills.version', '版本'],
  ['skills.author', '作者'],
  ['skills.tags', '标签'],
  ['skills.enable', '启用'],
  ['skills.disable', '禁用'],
  ['skills.edit', '编辑'],
  ['skills.delete', '删除'],
  ['skills.deleteConfirm', '确定要删除此技能吗？'],
  ['skills.save', '保存'],
  ['skills.cancel', '取消'],
  ['skills.saved', '已保存'],
  ['skills.saveFailed', '保存失败'],
  ['skills.loading', '加载中...'],
  ['skills.error', '加载失败'],
  ['skills.retry', '重试'],
  ['skills.search', '搜索技能'],
  ['skills.filter', '筛选'],
  ['skills.sort', '排序'],
  ['skills.install', '安装'],
  ['skills.uninstall', '卸载'],
  ['skills.installed', '已安装'],
  ['skills.available', '可用'],
  ['skills.details', '详情'],
  ['skills.configuration', '配置'],
  ['skills.permissions', '权限'],
  ['skills.dependencies', '依赖'],
  ['skills.examples', '示例'],
  ['skills.documentation', '文档'],
  ['skills.source', '源码'],
  ['skills.license', '许可证'],
  ['skills.rating', '评分'],
  ['skills.downloads', '下载次数'],
  ['skills.lastUpdated', '最后更新'],
  ['skills.compatibility', '兼容性'],
  ['skills.requirements', '要求'],
  ['skills.changelog', '更新日志'],
  ['skills.issues', '问题'],
  ['skills.support', '支持'],
  ['skills.feedback', '反馈'],
];
for (const [k, v] of sk) s(zh, k, v);

// ============ routine ============
const rt = [
  ['routine.history.title', '历史记录'],
  ['routine.history.noHistory', '暂无历史记录'],
  ['routine.history.loading', '加载中...'],
  ['routine.history.error', '加载失败'],
  ['routine.history.retry', '重试'],
  ['routine.history.runId', '运行 ID'],
  ['routine.history.status', '状态'],
  ['routine.history.startedAt', '开始时间'],
  ['routine.history.completedAt', '完成时间'],
  ['routine.history.duration', '持续时间'],
  ['routine.history.trigger', '触发器'],
  ['routine.history.viewDetails', '查看详情'],
  ['routine.history.export', '导出'],
  ['routine.history.refresh', '刷新'],
  ['routine.history.filter', '筛选'],
  ['routine.history.clearFilter', '清除筛选'],
  ['routine.history.search', '搜索'],
  ['routine.toasts.created', '例程已创建'],
  ['routine.toasts.updated', '例程已更新'],
  ['routine.toasts.deleted', '例程已删除'],
  ['routine.toasts.enabled', '例程已启用'],
  ['routine.toasts.disabled', '例程已禁用'],
  ['routine.toasts.started', '例程已启动'],
  ['routine.toasts.stopped', '例程已停止'],
  ['routine.toasts.paused', '例程已暂停'],
  ['routine.toasts.resumed', '例程已恢复'],
  ['routine.toasts.error', '操作失败'],
  ['routine.toasts.saveSuccess', '保存成功'],
  ['routine.toasts.saveFailed', '保存失败'],
  ['routine.toasts.deleteFailed', '删除失败'],
  ['routine.toasts.runStarted', '运行已开始'],
  ['routine.toasts.runCompleted', '运行已完成'],
  ['routine.toasts.runFailed', '运行失败'],
  ['routine.toasts.runCancelled', '运行已取消'],
  ['routine.composer.title', '例程编辑器'],
  ['routine.composer.name', '名称'],
  ['routine.composer.description', '描述'],
  ['routine.composer.trigger', '触发器'],
  ['routine.composer.schedule', '计划'],
  ['routine.composer.webhook', 'Webhook'],
  ['routine.composer.event', '事件'],
  ['routine.composer.manual', '手动'],
  ['routine.composer.steps', '步骤'],
  ['routine.composer.addStep', '添加步骤'],
  ['routine.composer.removeStep', '移除步骤'],
  ['routine.composer.reorderSteps', '重新排序步骤'],
  ['routine.composer.save', '保存'],
  ['routine.composer.cancel', '取消'],
  ['routine.composer.saved', '已保存'],
  ['routine.composer.saveFailed', '保存失败'],
  ['routine.composer.preview', '预览'],
  ['routine.composer.test', '测试'],
  ['routine.composer.run', '运行'],
  ['routine.nav.title', '例程导航'],
  ['routine.nav.all', '全部'],
  ['routine.nav.active', '活跃'],
  ['routine.nav.paused', '已暂停'],
  ['routine.nav.draft', '草稿'],
  ['routine.nav.archived', '已归档'],
  ['routine.nav.search', '搜索例程'],
  ['routine.nav.filter', '筛选'],
  ['routine.nav.sort', '排序'],
  ['routine.nav.create', '创建例程'],
  ['routine.detail.title', '例程详情'],
  ['routine.detail.loading', '加载中...'],
  ['routine.detail.error', '加载失败'],
  ['routine.detail.retry', '重试'],
  ['routine.detail.overview', '概览'],
  ['routine.detail.history', '历史'],
  ['routine.detail.settings', '设置'],
  ['routine.detail.run', '运行'],
  ['routine.detail.edit', '编辑'],
  ['routine.detail.delete', '删除'],
  ['routine.detail.enable', '启用'],
  ['routine.detail.disable', '禁用'],
  ['routine.detail.schedule', '计划'],
  ['routine.detail.lastRun', '上次运行'],
  ['routine.detail.nextRun', '下次运行'],
  ['routine.detail.status', '状态'],
  ['routine.detail.trigger', '触发器'],
  ['routine.detail.variables', '变量'],
  ['routine.detail.steps', '步骤'],
  ['routine.dirty.title', '未保存的更改'],
  ['routine.dirty.description', '您有未保存的更改。'],
  ['routine.dirty.save', '保存'],
  ['routine.dirty.discard', '放弃'],
  ['routine.dirty.cancel', '取消'],
  ['routine.policies.title', '策略'],
  ['routine.policies.retry', '重试策略'],
  ['routine.policies.timeout', '超时策略'],
  ['routine.policies.concurrency', '并发策略'],
  ['routine.policies.save', '保存'],
  ['routine.policies.cancel', '取消'],
  ['routine.groups.title', '分组'],
  ['routine.groups.noGroups', '暂无分组'],
  ['routine.groups.create', '创建分组'],
  ['routine.groups.name', '名称'],
  ['routine.groups.description', '描述'],
  ['routine.groups.save', '保存'],
  ['routine.groups.delete', '删除'],
  ['routine.sort.title', '排序'],
  ['routine.sort.name', '名称'],
  ['routine.sort.status', '状态'],
  ['routine.sort.lastRun', '上次运行'],
  ['routine.sort.createdAt', '创建时间'],
  ['routine.sections.editable.title', '可编辑部分'],
  ['routine.sections.editable.add', '添加'],
  ['routine.sections.editable.remove', '移除'],
  ['routine.sections.editable.save', '保存'],
  ['routine.sections.operate.title', '操作部分'],
  ['routine.sections.operate.run', '运行'],
  ['routine.sections.operate.pause', '暂停'],
  ['routine.sections.operate.resume', '恢复'],
  ['routine.sections.operate.stop', '停止'],
];
for (const [k, v] of rt) s(zh, k, v);

// ============ instanceSettings ============
const is_ = [
  ['instanceSettings.general.title', '通用设置'],
  ['instanceSettings.general.instanceName', '实例名称'],
  ['instanceSettings.general.instanceDescription', '实例描述'],
  ['instanceSettings.general.save', '保存'],
  ['instanceSettings.general.saved', '已保存'],
  ['instanceSettings.general.saveFailed', '保存失败'],
  ['instanceSettings.general.loading', '加载中...'],
  ['instanceSettings.general.error', '加载失败'],
  ['instanceSettings.general.retry', '重试'],
  ['instanceSettings.experimental.title', '实验性功能'],
  ['instanceSettings.experimental.description', '这些功能可能不稳定。'],
  ['instanceSettings.experimental.enable', '启用'],
  ['instanceSettings.experimental.disable', '禁用'],
  ['instanceSettings.experimental.enabled', '已启用'],
  ['instanceSettings.experimental.disabled', '已禁用'],
  ['instanceSettings.experimental.save', '保存'],
  ['instanceSettings.experimental.saved', '已保存'],
  ['instanceSettings.experimental.saveFailed', '保存失败'],
  ['instanceSettings.experimental.loading', '加载中...'],
  ['instanceSettings.experimental.error', '加载失败'],
  ['instanceSettings.experimental.warning', '警告：这些功能可能导致数据丢失。'],
  ['instanceSettings.experimental.confirm', '确认启用'],
  ['instanceSettings.experimental.cancel', '取消'],
  ['instanceSettings.profile.title', '个人设置'],
  ['instanceSettings.profile.name', '名称'],
  ['instanceSettings.profile.email', '邮箱'],
  ['instanceSettings.profile.avatar', '头像'],
  ['instanceSettings.profile.save', '保存'],
  ['instanceSettings.profile.saved', '已保存'],
  ['instanceSettings.profile.saveFailed', '保存失败'],
  ['instanceSettings.profile.loading', '加载中...'],
  ['instanceSettings.profile.error', '加载失败'],
  ['instanceSettings.profile.changePassword', '修改密码'],
  ['instanceSettings.profile.currentPassword', '当前密码'],
  ['instanceSettings.profile.newPassword', '新密码'],
  ['instanceSettings.profile.confirmPassword', '确认密码'],
  ['instanceSettings.profile.passwordChanged', '密码已修改'],
  ['instanceSettings.profile.passwordMismatch', '密码不匹配'],
  ['instanceSettings.heartbeats.title', '心跳监控'],
  ['instanceSettings.heartbeats.description', '监控系统健康状态。'],
  ['instanceSettings.heartbeats.status', '状态'],
  ['instanceSettings.heartbeats.lastCheck', '最后检查'],
  ['instanceSettings.heartbeats.interval', '间隔'],
  ['instanceSettings.heartbeats.enabled', '已启用'],
  ['instanceSettings.heartbeats.disabled', '已禁用'],
  ['instanceSettings.heartbeats.save', '保存'],
  ['instanceSettings.heartbeats.saved', '已保存'],
  ['instanceSettings.heartbeats.saveFailed', '保存失败'],
  ['instanceSettings.heartbeats.loading', '加载中...'],
  ['instanceSettings.heartbeats.error', '加载失败'],
  ['instanceSettings.heartbeats.test', '测试'],
  ['instanceSettings.heartbeats.testing', '测试中...'],
];
for (const [k, v] of is_) s(zh, k, v);

fs.writeFileSync(path.join(dir, 'zh-CN.json'), JSON.stringify(zh, null, 2) + '\n');
console.log('Batch B done: companySettings, skills, routine, instanceSettings translated.');
